name: Scheduled Task
on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 PM UTC
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: curl -X GET "https://myapp.com/api/task"
